### ISSUE TITLE
This cursor view is more clear on dark background than  light(white)

### ISSUE THREAD

**Issue by ceyhunn** [FadeMind/maia-cursor-theme#1]
It would be cool to make cursor view on light background as clear as  view on dark.

**Comment by FadeMind** [comment]
@varlesh could you please take a look at this in a free time? :> You are SVG master editor for me ;)

**Comment by varlesh** [comment]
@FadeMind Very cool work. 
Maybe better disable opacity for color `#192629` and possible change color to `#4d4e4b`
Another solution add more shadows - reduce opacity. For example to 40%:
```
sed -i s/opacity:0.2/opacity:0.4/g cursors.svg
```

**Comment by FadeMind** [comment]
@varlesh could you please prepare proper SVG fixes in pull request for testing? :> 

I made only one thing here (movin from original blue to manjaro's maia green) and CMakeScript hack for easly install ;)

**Comment by varlesh** [comment]
[src.tar.gz](https://github.com/FadeMind/maia-cursor-theme/files/1834807/src.tar.gz)

**Comment by FadeMind** [comment]
@varlesh thanks, I will take a look and test changes tomorrow. Please accept colaborator invitation ;)

**Comment by ceyhunn** [comment]
Great thanks to all of you. Awesome cursor theme!!
I think, this will be default Manjaro cursor theme. I use this in Manjaro Gnome.

**Comment by FadeMind** [comment]
Resolved via f91d843

@varlesh thanks for help.
